apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-v4-deployment
  labels:
    app: devops-v4-deployment
spec:
  selector:
    matchLabels:
      app: devops-v4-deployment
  replicas: 1
  template:
    metadata:
      name: devops-v4-deployment
      labels:
        app: devops-v4-deployment
    spec:
      containers:
        - name: devops-v4-deployment
          image: docker.io/ozangulll/devops-v4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080