kind: Service
apiVersion: v1
metadata:
  name: devops-v4-kubernetes
spec:
  type: NodePort
  selector:
    app: devops-v4-kubernetes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080